INSERT INTO USER(USER_NAME, MAIL, PASSWORD) VALUES('CAMI', 'CAMI@MAIL.DK', '1234');
INSERT INTO WISHLIST(USER_ID, NAME, DESCRIPTION) VALUES(1, 'JULEØNSKER', '2025');
INSERT INTO WISHLIST(USER_ID, NAME, DESCRIPTION) VALUES(1, 'FØDSELSDAG', ' OKTOBER 2025');
INSERT INTO WISH(WISHLIST_ID, NAME, DESCRIPTION, LINK, PRIS) VALUES(1, 'SKO', 'STR. 38', 'https://www.adidas.dk/handball-spezial-sko/BD7632.html', 399);
INSERT INTO WISH(WISHLIST_ID, NAME, DESCRIPTION, LINK, PRIS) VALUES(1, 'TRØJE', 'STR. M', 'WWW.TRØJE.DK', 199);
INSERT INTO WISH(WISHLIST_ID, NAME, DESCRIPTION, LINK, PRIS) VALUES(2, 'LAMPE', 'Verner Panton', 'WWW.vernerpanton.DK', 999);
INSERT INTO WISH(WISHLIST_ID, NAME, DESCRIPTION, LINK, PRIS) VALUES(1, 'SKO', 'STR. 38', 'https://www.adidas.dk/handball-spezial-sko/BD7632.html', 399);
INSERT INTO WISH(WISHLIST_ID, NAME, DESCRIPTION, LINK, PRIS) VALUES(1, 'TRØJE', 'STR. M', 'WWW.TRØJE.DK', 199);
INSERT INTO WISH(WISHLIST_ID, NAME, DESCRIPTION, LINK, PRIS) VALUES(2, 'LAMPE', 'Verner Panton', 'WWW.vernerpanton.DK', 999);

