CREATE DATABASE IF NOT EXISTS WISHLIST DEFAULT CHARACTER SET utf8;
USE WISHLIST;

DROP TABLE if EXISTS WISH;
DROP TABLE if EXISTS WISHLIST;
DROP TABLE if EXISTS USER;



CREATE TABLE USER(
	USER_ID INTEGER NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(50) UNIQUE NOT NULL,
    MAIL VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE WISHLIST(
	WISHLIST_ID INTEGER NOT NULL AUTO_INCREMENT,
	USER_ID INTEGER NOT NULL DEFAULT 1, 
    NAME VARCHAR(50) NOT NULL, 
    DESCRIPTION VARCHAR(200),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    PRIMARY KEY (WISHLIST_ID)
);


CREATE TABLE WISH(
	WISH_ID INTEGER NOT NULL AUTO_INCREMENT, 
    WISHLIST_ID INTEGER NOT NULL, 
    NAME VARCHAR(50) NOT NULL, 
    DESCRIPTION VARCHAR(200),
    LINK TEXT(200),
    PRIS INTEGER,
    FOREIGN KEY (WISHLIST_ID) REFERENCES WISHLIST(WISHLIST_ID),
    PRIMARY KEY (WISH_ID)
);


