DROP TABLE IF EXISTS WISH;
DROP TABLE IF EXISTS WISHLIST;

CREATE TABLE WISHLIST
(
    WISHLIST_ID INTEGER      NOT NULL AUTO_INCREMENT,
    NAME        VARCHAR(100) NOT NULL,
    PRIMARY KEY (WISHLIST_ID)
);

CREATE TABLE WISH
(
    WISH_ID     INTEGER     NOT NULL AUTO_INCREMENT,
    WISHLIST_ID INTEGER     NOT NULL,
    NAME        VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200),
    LINK        VARCHAR(200),
    PRIS        INTEGER,
    FOREIGN KEY (WISHLIST_ID) REFERENCES WISHLIST (WISHLIST_ID),
    PRIMARY KEY (WISH_ID)
);

INSERT INTO WISHLIST (NAME)
VALUES ('Jul');
INSERT INTO WISHLIST (NAME)
VALUES ('Fødselsdag');

INSERT INTO WISH(WISHLIST_ID, NAME, DESCRIPTION, LINK, PRIS)
VALUES (1, 'SKO', 'STR. 38', 'https://www.adidas.dk/handball-spezial-sko/BD7632.html', 399);

INSERT INTO WISH(WISHLIST_ID, NAME, DESCRIPTION, LINK, PRIS)
VALUES (1, 'TRØJE', 'STR. M', 'WWW.TRØJE.DK', 199);

INSERT INTO WISH(WISHLIST_ID, NAME, DESCRIPTION, LINK, PRIS)
VALUES (2, 'LAMPE', 'Verner Panton', 'WWW.vernerpanton.DK', 999);
